[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "client/.next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
[build]
  command = "npm run build"
  publish = "client/.next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
