name: CI

on:
  push:
    branches: [ main, new_branch, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Type Check
        run: npx tsc -p tsconfig.base.json --noEmit
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Package Netlify Function (tsc already built server)
        run: |
          echo "Packaging function directory"
          ls -R netlify/functions || true
      - name: Local Smoke (start express)
        run: |
          node server/dist/index.js &
          PID=$!
          sleep 2
          node server/scripts/smoke.js || (echo 'Smoke failed' && kill $PID && exit 1)
          kill $PID
